### ISSUE TITLE
Build failing

### ISSUE THREAD

**Issue by ibodrov** [oneops/build-wf#10]
Oneops Jenkins build fails with ClassNotFoundException in the workflow plugin:
From _build-wf/log/jenkins.log_
```
Jun 30, 2016 4:39:44 AM hudson.ExtensionFinder$GuiceFinder$FaultTolerantScope$1 error
WARNING: Failed to instantiate Key[type=org.jenkinsci.plugins.workflow.cps.CpsScmFlowDefinition$DescriptorImpl, annotation=[none]]; skipping this component
com.google.inject.ProvisionException: Guice provision errors:

1) Error injecting constructor, java.lang.NoClassDefFoundError: org/jenkinsci/plugins/workflow/steps/scm/SCMStep
  at org.jenkinsci.plugins.workflow.cps.CpsScmFlowDefinition$DescriptorImpl.<init>(CpsScmFlowDefinition.java:125)

1 error
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:52)
        at com.google.inject.Scopes$1$1.get(Scopes.java:65)
        at hudson.ExtensionFinder$GuiceFinder$FaultTolerantScope$1.get(ExtensionFinder.java:427)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
        at com.google.inject.internal.InjectorImpl$3$1.call(InjectorImpl.java:1005)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1051)
        at com.google.inject.internal.InjectorImpl$3.get(InjectorImpl.java:1001)
        at hudson.ExtensionFinder$GuiceFinder._find(ExtensionFinder.java:389)
        at hudson.ExtensionFinder$GuiceFinder.find(ExtensionFinder.java:380)
        at hudson.ClassicPluginStrategy.findComponents(ClassicPluginStrategy.java:388)
...
```
Steps to reproduce: follow the [docker image building instuctions](https://github.com/oneops/setup/blob/master/docker/README.md).

I tried to update plugin version in plugin.txt -- upgraded workflow plugins version from 1.4 to 1.9.
After that, build finished successfully.

**Comment by ibodrov** [comment]
Nvm,
